name: Build and deploy to Google Cloud Platform
on:
    push:
        branches: [main]
jobs:
    build-and-deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download files
              run: |
                pwd
                whoami

            - name: Install
              run: npm install
            
            - name: Build
              run: npm run build

            - name: Start
              run: pm2 start nextjs-gh