name: Build and deploy to Google Cloud Platform
on:
    push:
        branches: [main]
jobs:
    build-and-deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download files
              run: |
                cd /home/serg/webapps/nextjs-gh
                git pull

            - name: Install
              run: |
                cd /home/serg/webapps/nextjs-gh
                npm install
            
            - name: Build
              run: |
                cd /home/serg/webapps/nextjs-gh
                npm run build

            - name: Start
              run: pm2 start nextjs-gh